repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
   - id: nbqa-isort
     additional_dependencies: [ isort==5.6.4 ]
   - id: nbqa-pyupgrade
     additional_dependencies: [pyupgrade==2.7.3]
   - id: nbqa-ruff
     additional_dependencies: [ ruff ]
   - id: nbqa-black
     additional_dependencies: [black==20.8b1]
